### ISSUE TITLE
I am interested about your work

### ISSUE THREAD

**Issue by MarisaKirisame** [ldionne/hana-thesis#1]
Can you describe it briefly? BTW what kinds of research field is TMP considered in? Generative Programming or just Programming Language Theory?

**Comment by ldionne** [comment]
You might be familiar with the way a subset of Haskell can be formalized using category theory. The basic idea behind this paper is to do the same with the Hana category instead of the Hask category.

While the objects of Hask are types and the morphisms are functions, objects in Hana are simply generalized types (similar to Fusion tags) and the morphisms are generic functions whose domain is all the objects with a given generalized type. Once this is set up properly, the rest follows naturally and is very similar to what happens with Haskell.

I initially had plans to translate this work as-is. I think I won't do it, but I will instead write a series of blog posts on [my blog](http://ldionne.com) this summer when I get the time. If you are interested in the topic, you should stay tuned.

I am not really sure what kind of research field this is in. I would say TMP is generative programming (amongst others), and the rest is applied category theory. The "programming language theory" tag probably describes the mix of the two pretty well.

**Comment by MarisaKirisame** [comment]
Thank you. Will stay tuned. Too bad I can't read french... :)
